### ISSUE TITLE
update from 116 to 1.1.1.7 doesn't work

### ISSUE THREAD

**Issue by rmurawka01** [lucagrippa/obsidian-ai-tagger#15]
error from console  when try to update : 
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

**Comment by DesignMike** [comment]
I get the same error

**Comment by lucagrippa** [comment]
Thank you both, working on a fix right now

**Comment by lucagrippa** [comment]
Should be all fixed, please let me know if this works for you both now

**Comment by DesignMike** [comment]
Thanks so much :)

Best regards,

Mike Belanger

Owner

Designful Inc
(613) 699-6233
***@***.***
Designful.ca <https://designful.ca/>
Ottawa, Canada
