### ISSUE TITLE
The baseUrl is not taking effect, displaying "Incorrect API key. Please check your API key."

### ISSUE THREAD

**Issue by Hwenyi** [lucagrippa/obsidian-ai-tagger#18]
I make sure the relevant model is integrated into my relay service and operates seamlessly with other plugins and applications. The issue shouldn't lie within the relay service itself.

I've examined main.js and tried replacing api.openai.com directly, leaving baseUrl blank, but this method didn't yield results either.

My baseUrl is set as https://aaa.bbb.ccc/v1, including variations with and without '/v1'.

Upon clicking to generate content, an error immediately surfaces.

Thank you for creating this plugin; your efforts are appreciated. Could you review the logic for verifying the api_key when convenient? If further error details are needed, I'm eager to help resolve any bugs."

**Comment by Genv1er** [comment]
I have the same problem.🤔

**Comment by KrystalC** [comment]
me too

**Comment by A-wels** [comment]
When using ollama on a server with the custom base url set, the requests are still send to localhost:
>POST http://127.0.0.1:11434/api/chat

**Comment by lucagrippa** [comment]
Looking into this, thank you all for your comments

**Comment by lucagrippa** [comment]
Just pushed a fix in 1.2.2, this should solve all of the problems regarding custom base URLs

**Comment by A-wels** [comment]
I can confirm that the update fixes my issue with ollama. Thank you!
