### ISSUE TITLE
Feature request: Add a openai base url so one can query custom compatible LLM servers

### ISSUE THREAD

**Issue by lstep** [lucagrippa/obsidian-ai-tagger#2]
I don't know the javascript/typescript version of @langchain/openai, but would it be possible to add an api base url parameter alongside the `openAIApiKey` parameter so we could use AI Tagger with custom OpenAI compatible local LLM servers?

**Comment by lucagrippa** [comment]
Just went ahead and added support for custom Base URLs. Thanks for the feature request! Let me know if there are any issues with the latest release.
