### ISSUE TITLE
Usage of langfuse.com

### ISSUE THREAD

**Issue by A-wels** [lucagrippa/obsidian-ai-tagger#20]
Hello,
can you tell me what langfuse.com is used for in the code? What data is send to their servers?
Is any content of the notes included in the callback in llm.ts (l. 158)?

Also, your public and secret key for the API is included in the repo. It this intentional?

**Comment by lucagrippa** [comment]
Hi @A-wels, thank you so much for bringing this to my attention.

I just removed Langfuse in the latest release. I was using it to debug the LLM's outputs during testing and I accidentally left it in the code. The API keys have been deleted so even if users do not update none of the data will reach Langfuse's servers. 

I never intend to collect any data on AI Tagger's users now or in the future. 

Thanks again for pointing this out.

**Comment by A-wels** [comment]
Thanks for clarifying! I think we've all accidentally left debug code in our published work at some point...

**Comment by marcklingen** [comment]
Langfuse maintainer here

Just fyi, if you do not specify credentials / host for the Langfuse instrumentation, no data is logged. Thus you could keep instrumentation in production code without risking that data is logged.

Also, you can easily run Langfuse on your local machine via [docker compose](https://langfuse.com/docs/deployment/local) or add this to the documentation if someone wants to look at traces of what [obsidian-ai-tagger](https://github.com/lucagrippa/obsidian-ai-tagger) is doing.

Example: Langflow which allows users to enable logging by via environment variables ([docs](https://docs.langflow.org/integrations-langfuse)).
