### ISSUE TITLE
Missing Hotkey and Ribbon button

### ISSUE THREAD

**Issue by FeliksMarksen** [lucagrippa/obsidian-ai-tagger#23]
After updating to the latest release the assigned hotkey got lost and can't get reassigned. 

Also the button at the Ribbon vanished. 
So there is no way to generate Tags 

Additionally I had to reassign a new Openai Api Key, which throws the error that the key format is invalid. (I just copied it from openai...)

**Comment by lucagrippa** [comment]
Hey @FeliksMarksen, I just pushed an update (v1.2.3) that should fix this OpenAI API key error.

As for the ribbon vanishing, this has happened to me during development. Usually activating and deactivating the plugin in the "Community plugins" tab of the Obsidian settings will make the Ribbon icon reappear.

Let me know if there are any other issues :)
