### ISSUE TITLE
Not operational after obsidian install

### ISSUE THREAD

**Issue by archizoo** [lucagrippa/obsidian-ai-tagger#26]
Installed, enabled and inserted OpenAI API key, selected model. The "wand" does not appear in the left panel and the plugin does not seem to operate.

**Comment by archizoo** [comment]
The "wand" appeared on restart. Now, "error occurred while generating tags."

**Comment by refidAc** [comment]
Tried with 


Ollama | Mistral Nemo | 128K | Open Source
-- | -- | -- | --
Ollama | Qwen 2.5 | 128K | Open Source

Just says "Generating Tags" .. "Error: Check if Ollama is running and model is
installed"

It definitely is as another plugin can connect.

**Comment by lucagrippa** [comment]
@refidAc Sorry for the issues, in the most recent version of the plugin (1.2.5) I just pushed a fix. Hope this helps :)
