### ISSUE TITLE
Current version always creates "null" tag

### ISSUE THREAD

**Issue by ianTevesAcc** [lucagrippa/obsidian-ai-tagger#4]
As the title says the current plugin version generates "null" as a tag.

**Comment by ianTevesAcc** [comment]
Yes unfortunately. The AI tagger works well and gives proper tags relative to the current note but a null tag is always generated first before adding other tags.

This img shows tags being created but "null" being added first before the actual tags relative to the note.
It's easy to work around; you just have to remove the null tag every time the AI Tagger is run. I just wanted to let you know.
[image](https://github.com/lucagrippa/obsidian-ai-tagger/assets/105651670/6a9cb916-4d9c-446b-b4c1-5e23d9ec6be9)

**Comment by lucagrippa** [comment]
Hi @ianTevesAcc I just released a new version of the plugin that should fix this issue. Let me know if the fix is not working. If you come across more bugs or if you want to request features feel free to open another issue.

**Comment by ianTevesAcc** [comment]
It's weird. For some reason it cant detect the AI Model.

I just updated and gave it a new open ai api key and set the Model to be OpenAI GPT-3.4 Turbo.
It gave me this error. Is this happening on your end? @lucagrippa

plugin:terminal:115 
Error while generating tags: Error: Error getting model.
    at getLlm (plugin:ai-tagger:24585:11)
    at Object.editorCallback (plugin:ai-tagger:24658:21)
    at e.mobileOnly.zt.isMobile.e.checkCallback (app.js:1:1988281)
    at oK (app.js:1:1987579)
    at e.executeCommand (app.js:1:1989143)
    at e.onTrigger (app.js:1:1164833)
    at e.handleKey (app.js:1:757237)
    at e.handleKey (app.js:1:757350)
    at t.handleKey (app.js:1:757559)
    at e.onKeyEvent (app.js:1:758493)
| | | |
|---|---|---|
| eval | @ | plugin:terminal:115 |
| c | @ | plugin:terminal:111 |
| editorCallback | @ | plugin:ai-tagger:24671 |
| e.mobileOnly.zt.isMobile.e.checkCallback | @ | app.js:1 |
| oK | @ | app.js: |
| e.executeCommand | @ | app.js:1 |
| e.onTrigger | @ | app.js:1 |
| e.handleKey | @ | app.js:1 |
| e.handleKey | @ | app.js:1 |
| t.handleKey | @ | app.js:1 |
| e.onKeyEvent | @ | app.js:1 |

**Comment by ianTevesAcc** [comment]
I switched back to vers 1.0.4
The plugin works here as well as the null bug not being present.

**Comment by lucagrippa** [comment]
I just pushed another release. This should fix that "Error getting model" bug that was present. Thank you for working with me to fix this, I really appreciate it!

**Comment by ianTevesAcc** [comment]
Awesome!
